#!/bin/sh
# Xsetup - run as root before the login dialog appears
# dir: /usr/share/sddm/scripts/Xsetup
xrandr > /tmp/test.txt

xrandr --output DP-0 --primary
xrandr --output DP-4 --off
xrandr --output HDMI-0 --off
