-- Generated by nwg-displays on 2026-09-23 at 15:43:18. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1920x1080@239.76",
    position = "5120x913",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "DP-2",
    mode = "2560x1440@239.97",
    position = "2560x553",
    scale = 1,
    vrr = 0
})
hl.monitor({
    output = "DP-3",
    mode = "2560x1440@164.96",
    position = "0x553",
    scale = 1,
    vrr = 0
})
