-- Generated by nwg-displays on 2026-09-23 at 15:44:27. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-2",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "DP-3",
    default = true
})
hl.workspace_rule({
    workspace = "3",
    monitor = "DP-1",
    default = true
})

